### ISSUE TITLE
Failed to activate the open-in-browser package

### ISSUE THREAD

**Issue by mindreeper2420** [magbicaleman/open-in-browser#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [open-in-browser](https://github.com/magbicaleman/open-in-browser) package, v0.4.4

### Stack Trace

Failed to activate the open-in-browser package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/adamjolicoeur/.atom/packages/open-in-browser/lib/open-in-browser.coffee:8:24)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:270:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -2:49.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-shellscript",
      "language-sass",
      "language-ruby-on-rails",
      "language-xml",
      "language-yaml",
      "language-toml",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-objective-c",
      "language-go",
      "language-gfm",
      "language-c",
      "language-coffee-script",
      "deprecation-cop",
      "highlight-line"
    ],
    "audioBeep": false,
    "projectHome": "/Users/adamjolicoeur/Documents/Work/hubui",
    "themes": [
      "atom-dark-ui",
      "seti-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
css-color-highlighting, v0.2.4
highlight-css-color, v1.3.0
language-jade, v0.4.0
open-in-browser, v0.4.4
seti-monokai, v0.3.1
show-in-folder, v0.1.0

# Dev
No dev packages
```

**Comment by magbicaleman** [comment]
@mindreeper2420 this should be fixed.
