### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by jeffreylieu** [magbicaleman/open-in-browser#47]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [open-in-browser](https://github.com/magbicaleman/open-in-browser) package 0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/jefflieu/.atom/packages/open-in-browser/lib/open-in-browser.coffee:15

TypeError: Cannot read property 'getPath' of undefined
    at Object.getFilePath (/packages/open-in-browser/lib/open-in-browser.coffee:15:55)
    at Object.openEditor (/packages/open-in-browser/lib/open-in-browser.coffee:18:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -0:41 open-in-browser:open (div.lines)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.7 
intentions 1.1.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-stylelint 3.10.0 
linter-ui-default 1.6.0 
open-in-browser 0.5.2 
react 0.16.2 
```

**Comment by Seaside-Dev** [comment]
Still open. :(
Here's mine after Atom update .

TypeError: Cannot read property 'getPath' of undefined
    at Object.getFilePath (/Users/vee/.atom/packages/open-in-browser/lib/open-in-browser.coffee:15:55)
    at Object.openEditor (/Users/vee/.atom/packages/open-in-browser/lib/open-in-browser.coffee:18:12)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349858)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348333)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:654926)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:662310)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)

**Comment by matippetts** [comment]
### Describe the bug
The function `getFilePath()` [in open-in-browser.coffee](https://github.com/magbicaleman/open-in-browser/blob/0ab814320f8f27ab22624a590b84d96dd55e14bf/lib/open-in-browser.coffee#L15) uses method-chaining to get the file path to open. This raises an unchecked exception when [Workspace.getActiveTextEditor()](https://atom.io/docs/api/v1.34.0/Workspace#instance-getActiveTextEditor) returns `'undefined'` instead of the expected object.

The `open-in-browser:open` command [is registered](https://github.com/magbicaleman/open-in-browser/blob/0ab814320f8f27ab22624a590b84d96dd55e14bf/lib/open-in-browser.coffee#L10) for activation with the key `'atom-text-editor'`. The seemingly reasonable assumption is then that if the command is enabled, there is an active text editor. But this is not always the case -- as when a Pane item which is not a `TextEditor` object creates a child which is.

Here is an example involving the Markdown Preview plugin, which creates child `TextEditor` instances to handle code highlighting:

### Steps to Reproduce

1. Open a markdown file
2. Create a code block or HTML &lt;pre&gt; element with some content
3. Activate **Markdown Preview** (default keybinding: `ctrl-shift-M`)
4. In the preview pane, right-click inside the code block
5. In the context menu, click on **'Open in Browser'**

**Expected behavior:** The markdown file should open in the default system editor.

**Actual behavior:** Atom displays an error dialog.

### Screenshots

The 'Open in Browser' command enabled, when it shouldn't be:
![Open in Browser available from preview pane](
![screenshot_wrong-context-menu-in-markdown-preview_2019-01-22](https://user-images.githubusercontent.com/13559540/51619642-c9579f00-1efe-11e9-9835-044bb92f6d3c.png)
)

The error reported by the NotificationManager:
![Error dialog](
![screenshot_open-in-browser_issue-47](https://user-images.githubusercontent.com/13559540/51619654-ce1c5300-1efe-11e9-8305-5dcd7e9009d9.png)
)

**Comment by matippetts** [comment]
Submitted pull request: #71
