### ISSUE TITLE
Failed to load the open-in-browser package

### ISSUE THREAD

**Issue by beardaintweird** [magbicaleman/open-in-browser#51]
[Enter steps to reproduce:]

1. Clone open-in-browser package into ~../.atom/packages
2. Open atom

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [open-in-browser](https://github.com/magbicaleman/open-in-browser) package 0.5.2

### Stack Trace

Failed to load the open-in-browser package

```
At Cannot find module 'opn'

Error: Cannot find module 'opn'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/open-in-browser/lib/open-in-browser.coffee:2:7)
    at /packages/open-in-browser/lib/open-in-browser.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at /private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /private/var/folders/6b/t3f2wywj5cl24l2y81wcn_30sg8drb/T/AppTranslocation/9548CFC6-6B1F-4EFD-A5A4-03A5CB863C10/d/Atom.app/Contents/Resources/app/src/atom-environment.js:812:34
```

### Commands

```
     -0:37.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
open-in-browser 0.5.2 
```

**Comment by i-am-nick** [comment]
Ditto

**Comment by magbicaleman** [comment]
It seems that the npm install is not happening on Atom's end. Thank you.
