### ISSUE TITLE
broken in 1.21.1?

### ISSUE THREAD

**Issue by neptunerx** [magbicaleman/open-in-browser#56]
seems broken in 1.21.1

Error: Expected a `target`
    at module.exports (/Users/user/.atom/packages/open-in-browser/node_modules/opn/index.js:9:25)
    at Object.open (/Users/user/.atom/packages/open-in-browser/lib/open-in-browser.coffee:24:5)
    at Object.openTreeView (/Users/user/.atom/packages/open-in-browser/lib/open-in-browser.coffee:21:6)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
Close All

**Comment by sompylasar** [comment]
Duplicate of https://github.com/magbicaleman/open-in-browser/issues/50
