### ISSUE TITLE
Failed to open in browser - Error: Exited with code 1

### ISSUE THREAD

**Issue by clayms** [magbicaleman/open-in-browser#64]
When using `ctrl`+`shift`+`Q` or right-clicking and selecting `Open in Browser` , atom reports the following error.

```
Error: Exited with code 1
    at ChildProcess.<anonymous> (C:\Users\clay.stevens\.atom\packages\open-in-browser\node_modules\opn\index.js:83:13)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```
Have checked that the file opens in my default browser - Chrome.

Windows 10
atom 1.25.0 x64
open-in-browser 0.5.2
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by clayms** [comment]
Should be noted that using open-for-browser works for other file types.

**Comment by silvianayaa95** [comment]
Hi clayms 
I am having the same problem, could you fix it?

**Comment by clayms** [comment]
Not using Atom anymore, switched to VS Code.
