### ISSUE TITLE
Error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by ClarkTNA** [magbicaleman/open-in-browser#77]
Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I don't know what it is, I just getting started, please help

**Comment by pankaj5cds** [comment]
I have also the same issue.
